version: '3'
services:
  jpnb:
    restart: always
    ports:
      - 8989:8888
    volumes:
      - ./data:/home/jovyan
    image: jupyter/minimal-notebook
  redis:
    restart: always
    expose:
      - 6379
    image: redis:latest
